### ISSUE TITLE
Support optin

### ISSUE THREAD

**Issue by sue445** [sue445/activerecord-simple_index_name#11]
# Now
if required , all index are shorten

# New feature
* choose default shorten mode
  * ON: not changed
  * OFF: default is not shorten, but can enable shorten index in specify migration

# TODO
* [x] [config] auto_shorten #13
* [x] [migration] enable_shorten #12
* [x] [migration] disable_shorten #12

**Comment by sue445** [comment]
release will 0.2.0
